version: "3.7"
services:
  db:
    container_name: "db"
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_collector
    ports:
      - "5433:5432"

  alembic_migrations:
    container_name: "alembic_migrations"
    image: alembic_migrations
    environment:
      ALEMBIC_DATABASE_URL: "postgresql://postgres:postgres@db/weather_collector"
    build:
      context: .
      dockerfile: DockerfileAlembic
    depends_on:
      - db


  app_init:
    container_name: "app_init"
    image: app_init
    environment:
      DB_URL: "postgresql+asyncpg://postgres:postgres@db:5432/weather_collector"
      OXILOR_API_KEY: "arRcNuwfAkEtjdesIT4_3e4mbdJ249"
    build:
      context: .
      dockerfile: DockerfileInit
    depends_on:
      - alembic_migrations

  app_collect:
    container_name: "app_collect"
    image: app_collect
    environment:
      DB_URL: "postgresql+asyncpg://postgres:postgres@db:5432/weather_collector"
      OPENWEATHER_API_KEY: "b9b9fe45509f0497d07232d844b22aeb"
    build:
      context: .
      dockerfile: DockerfileCollect
    depends_on:
      - app_init