"""add weathers.created_at

Revision ID: 788a96b48b4c
Revises: b89bbdcf2fd6
Create Date: 2023-07-08 01:34:28.821302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '788a96b48b4c'
down_revision = 'b89bbdcf2fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities_created_at',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('created_at')
    )
    op.drop_table('city_created_at')
    op.add_column('weathers', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weathers', 'created_at')
    op.create_table('city_created_at',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('created_at', name='city_created_at_pkey')
    )
    op.drop_table('cities_created_at')
    # ### end Alembic commands ###
